apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: node-exporter
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels: 
      app: exporter
      role: monitoring
  template:
    metadata:
      labels:
        app: exporter
        role: monitoring
    spec:
      tolerations:
      - operator: "Exists"
        effect: "NoSchedule"
      containers:
      - image: alpine:latest
        name: node-exporter
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/healthy
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /apt/ready
            port: 3000
          initialDelaySeconds: 20
          timeoutSeconds: 10
          periodSeconds: 15
          failureThreshold: 3
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "120Mi"
            cpu: "200m"
        env:
        - name: MY_INT_VARIABLE
          value: "5"
        - name: MY_STRING_VARIABLE
          value: "Hello"
        - name: MY_BOOLEAN_VARIABLE
          value: "true"
